module.exports = [
  "apple", "banana", "guitar", "elephant", "pizza", "rocket", "castle", "dragon",
  "umbrella", "bicycle", "penguin", "volcano", "robot", "sandwich", "octopus",
  "ladder", "campfire", "mountain", "butterfly", "skateboard", "telescope",
  "cactus", "waterfall", "helicopter", "snowman", "lighthouse", "kangaroo",
  "pancake", "dinosaur", "spaceship", "mermaid", "pirate", "wizard", "vampire",
  "zombie", "ninja", "knight", "dragonfly", "jellyfish", "hedgehog", "raccoon",
  "avocado", "pretzel", "taco", "sushi", "pineapple", "watermelon", "coconut",
  "trumpet", "violin", "drum", "piano", "accordion", "windmill", "tractor",
  "submarine", "airplane", "train", "scooter", "surfboard", "parachute",
  "compass", "anchor", "treasure", "map", "crown", "shield", "sword", "arrow",
  "bow", "cannon", "tornado", "rainbow", "lightning", "iceberg", "glacier",
  "desert", "jungle", "beehive", "spiderweb", "scarecrow", "haystack",
  "barn", "tractor beam", "unicorn", "griffin", "phoenix", "mummy",
  "skeleton", "ghost", "witch", "cauldron", "broomstick", "lantern",
  "candle", "chandelier", "throne", "moat", "drawbridge", "catapult",
];
